# Generated by Django 2.2.20 on 2021-05-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('exchange', models.CharField(choices=[('NASDAQ', 'NASDAQ'), ('NYSE', 'NYSE'), ('BSE', 'BSE'), ('NSE', 'NSE')], max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('subscription_fmv', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Subscription FMV')),
                ('purchase_fmv', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Purchase FMV')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Purchase Price')),
                ('shares_purchased', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Shares Purchased')),
                ('purchase_conversion_rate', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Purchase Conversion Rate')),
                ('total_purchase_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total Purchase Price')),
                ('sell_date', models.DateField(blank=True, null=True, verbose_name='Sell Date')),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Sell Price')),
                ('sell_conversion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Sell Conversion Rate')),
                ('total_sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Total Sell Price')),
                ('user', models.IntegerField()),
                ('goal', models.IntegerField(blank=True, null=True)),
                ('latest_conversion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Latest Conversion Price')),
                ('latest_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Latest Price')),
                ('latest_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Latest Value')),
                ('as_on_date', models.DateField(blank=True, null=True, verbose_name='As On Date')),
                ('gain', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Gain')),
            ],
            options={
                'unique_together': {('purchase_date', 'symbol')},
            },
        ),
    ]
