# Generated by Django 2.2.20 on 2021-05-01 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSUAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('NASDAQ', 'NASDAQ'), ('NYSE', 'NYSE'), ('BSE', 'BSE'), ('NSE', 'NSE')], max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('user', models.IntegerField()),
                ('goal', models.IntegerField(blank=True, null=True)),
                ('award_date', models.DateField(verbose_name='Award Date')),
                ('award_id', models.CharField(max_length=20)),
                ('shares_awarded', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Awarded')),
            ],
        ),
        migrations.CreateModel(
            name='RestrictedStockUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vest_date', models.DateField(verbose_name='Vest Date')),
                ('fmv', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='FMV')),
                ('aquisition_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Aquisition Price')),
                ('shares_vested', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Vested')),
                ('shares_for_sale', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Available For Sell')),
                ('total_aquisition_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total Aquisition Price')),
                ('sell_date', models.DateField(blank=True, null=True, verbose_name='Sell Date')),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Sell Price')),
                ('sell_conversion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Sell Conversion Rate')),
                ('total_sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Total Sell Price')),
                ('notes', models.CharField(blank=True, max_length=80, null=True)),
                ('latest_conversion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Latest Conversion Price')),
                ('latest_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Latest Price')),
                ('latest_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Latest Value')),
                ('as_on_date', models.DateField(blank=True, null=True, verbose_name='As On Date')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsu.RSUAward')),
            ],
            options={
                'unique_together': {('award', 'vest_date')},
            },
        ),
    ]
