# Generated by Django 2.2.20 on 2021-05-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PEMonthy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(max_length=60)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('pe_avg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pe_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pe_min', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('index_name', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PBMonthy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(max_length=60)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('pb_avg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pb_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pb_min', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('index_name', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=60)),
                ('symbol', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=6000)),
                ('date', models.DateField()),
                ('link', models.CharField(max_length=6000)),
                ('source', models.CharField(max_length=60)),
            ],
            options={
                'unique_together': {('exchange', 'symbol', 'text', 'date', 'source')},
            },
        ),
    ]
