# Generated by Django 2.2.24 on 2021-09-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date Of Birth')),
                ('notes', models.CharField(blank=True, max_length=60, null=True)),
                ('short_name', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
        ),
    ]
